n1 = float(input('Digite o primeiro valor: '))
n2 = float(input('Digite o segundo valor: '))
n3 = float(input('Digite o terceiro valor: '))
media = ((n1 + n2 + n3)/3)
print(f'A média aritmética entre {n1}, {n2} e {n3} é {media}')